apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  labels:
    app: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            valueFrom:
                secretKeyRef:
                    name: fiap-mssql-secret
                    key: SA_PASSWORD
          volumeMounts:
            - name: mssql-storage
              mountPath: /var/lib/mssql
      volumes:
      - name: mssql-storage
        persistentVolumeClaim:
          claimName: fiap-mssql-pvc