apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-consumer-deployment
  labels:
    app: fiap-consumer
    instance: fiap-consumer-app
  annotations:
    description: "Este é a instância do microsserviço consumer da minha aplicação."
    autor: Grupo 31
spec:
  replicas: 2  # Número de réplicas do Consumer
  selector:
    matchLabels:
      app: fiap-consumer
  template:
    metadata:
      labels:
        app: fiap-consumer
    spec:
      containers:
        - name: fiap-consumer
          image: letticialuize/gerenciamentocontatosrefatorado-consumer:1.4
          ports:
            - containerPort: 3001
          env:
          - name: SA_PASSWORD
            valueFrom:
                secretKeyRef:
                    name: fiap-mssql-secret
                    key: SA_PASSWORD
          - name: ConnectionStrings__DefaultConnection
            value: "Data Source=mssql-service,1433;Initial Catalog=Contato;User Id=sa; Password=$(SA_PASSWORD);Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;"

          envFrom:
            - configMapRef:
                name: fiap-configmap    
          volumeMounts:
            - name: shared
              mountPath: /app/data  # Local onde o volume será montado
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: fiap-mssql-pvc  # PVC para persistência dos dados
