apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
spec:
  capacity:
    storage: 1Gi  
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: fiap-local-storage-class  
  volumeMode: Filesystem 
  hostPath:
    path: "/mnt/data/rabbitmq"  # Diretório no host onde os dados são armazenados
