apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fiap-mssql-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi  
  storageClassName: fiap-local-storage-class  

  
  
# Funciona em conjunto com o PV, o PV encontra o PVC pelo "acessModes" e "storageClassName"