apiVersion: v1
kind: Service
metadata:
    name: svc-fiap-consumer-nodeport
spec:
    type: NodePort
    ports:
        - port: 80
          targetPort: 3001
          nodePort: 31301
    selector:
        app: fiap-consumer