apiVersion: v1
kind: Service
metadata:
  name: mssql-service
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433  # Porta que será exposta dentro do Kubernetes
      targetPort: 1433  # Porta interna do container MSSQL
  type: NodePort
