FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY . .
RUN dotnet publish TechChallengeFase3.Producer/TechChallengeFase3.Producer.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out .

EXPOSE 3000

ENTRYPOINT ["dotnet", "TechChallengeFase3.Producer.dll"]